local terminal = require("core.terminal")

vim.keymap.set("n", "<ESC><ESC>", ":<C-u>nohlsearch<CR>")
vim.keymap.set("n", "<leader>cf", ":CopyCurrentFileRelativePath<CR>")
vim.keymap.set("n", "<leader>cd", ":CopyCurrentFileRelativePath!<CR>")
vim.keymap.set("n", "<space>]", ":cd %:h<CR>")
vim.keymap.set("n", "<leader><c-r>", ":ReloadCurrentLuaFile<CR>")
vim.keymap.set("n", "gx", function() return ":silent execute '!xdg-open' shellescape(expand('<cfile>'), 1)<cr>" end)
vim.keymap.set("n", "<leader><c-t>", ":tabe %<cr>")
vim.keymap.set("n", "Ov", ":OpenPathUnderCursor vsp<CR>")
vim.keymap.set("n", "Os", ":OpenPathUnderCursor sp<CR>")
vim.keymap.set("n", "Ot", ":OpenPathUnderCursor tabe<CR>")
vim.keymap.set("n", "<leader>frn", ":RenameFile<CR>")
vim.keymap.set("n", "<leader>ca", ":CreateNewFile<CR>")
vim.keymap.set("n", "j", "gj")
vim.keymap.set("n", "k", "gk")
vim.keymap.set("v", "v", "$h")
vim.keymap.set("n", "<C-j>", "<C-w><C-j>")
vim.keymap.set("n", "<C-k>", "<C-w><C-k>")
vim.keymap.set("n", "<C-h>", "<C-w><C-h>")
vim.keymap.set("n", "<C-l>", "<C-w><C-l>")
vim.keymap.set("n", "<leader>tt", ":tabe<CR>:terminal<CR>")
vim.keymap.set("n", "<leader>tv", ":vsp<CR>:terminal<CR>")
vim.keymap.set("n", "<leader>ts", ":botright 20split<CR>:terminal<CR>")
vim.keymap.set("n", "<leader>ds", function() terminal.open_within_current_dir("20split") end)
vim.keymap.set("n", "<leader>dt", function() terminal.open_within_current_dir("tabnew") end)
vim.keymap.set("n", "<leader>dv", function() terminal.open_within_current_dir("vsplit") end)
vim.keymap.set("n", "<leader>n", function() terminal.open_within_current_dir("20split", "ls -la") end)
vim.keymap.set("n", "<C-\\>", terminal.toggle, { silent = true })
