local terminal = require("core.terminal")
local neogit = require("neogit")
local qf_finder = require("local_plugins.quickfix.app.finder")

vim.keymap.set("n", "<ESC><ESC>", ":<C-u>nohlsearch<CR>")
vim.keymap.set("n", "<leader>cf", ":CopyCurrentFileRelativePath<CR>", { silent = true })
vim.keymap.set("n", "<leader>cd", ":CopyCurrentFileRelativePath!<CR>", { silent = true })
vim.keymap.set("n", "<leader>cF", ":CopyCurrentFileAbsolutePath<CR>", { silent = true })
vim.keymap.set("n", "<leader>cD", ":CopyCurrentFileAbsolutePath!<CR>", { silent = true })
vim.keymap.set("n", "gx", function() return ":silent execute '!xdg-open' shellescape(expand('<cfile>'), 1)<cr>" end)
vim.keymap.set("n", "<leader><C-t>", ":tabe %<CR>")
vim.keymap.set("n", "<leader>Ov", ":OpenPathUnderCursor vsp<CR>")
vim.keymap.set("n", "<leader>Os", ":OpenPathUnderCursor sp<CR>")
vim.keymap.set("n", "<leader>Ot", ":OpenPathUnderCursor tabe<CR>")
vim.keymap.set("n", "j", "gj")
vim.keymap.set("n", "k", "gk")
vim.keymap.set("v", "v", "$h")
vim.keymap.set("n", "<C-j>", "<C-w><C-j>")
vim.keymap.set("n", "<C-k>", "<C-w><C-k>")
vim.keymap.set("n", "<C-h>", "<C-w><C-h>")
vim.keymap.set("n", "<C-l>", "<C-w><C-l>")
vim.keymap.set("n", "<leader>tt", ":tabe<CR>:terminal<CR>", { silent = true })
vim.keymap.set("n", "<leader>tv", ":vsp<CR>:terminal<CR>", { silent = true })
vim.keymap.set("n", "<leader>ts", ":botright 20split<CR>:terminal<CR>", { silent = true })
vim.keymap.set("n", "<leader>ds", function() terminal.open_within_current_dir("split") end)
vim.keymap.set("n", "<leader>dt", function() terminal.open_within_current_dir("tabnew") end)
vim.keymap.set("n", "<leader>dv", function() terminal.open_within_current_dir("vsplit") end)
vim.keymap.set("n", "<leader>n", function() terminal.open_within_current_dir("20split", "ls -la") end)
vim.keymap.set("n", "<C-\\>", terminal.toggle)
vim.keymap.set("n", "<leader>wh", ":ResizeWindowHorizontal<space>")
vim.keymap.set("n", "<leader>wv", ":ResizeWindowVertical<space>")
vim.keymap.set("n", "<leader>rn", ":RelativeNumberToggle<CR>", { silent = true })
vim.keymap.set("n", "<leader>gw", function() qf_finder.live_grep(vim.fn.expand("<cword>")) end, { silent = true })
vim.keymap.set("n", "<Leader>gg", qf_finder.live_grep, { silent = true })
vim.keymap.set("n", "<leader>b", qf_finder.find_recent_buffers, { silent = true })
vim.keymap.set("n", "<leader>/", qf_finder.buffer_search)
vim.keymap.set("n", "<leader>o", qf_finder.find_files, { silent = true })
