#!/bin/sh

function usage
{
  echo "./android-linux-terminal [init|setup]"
}

LOCAL_BIN="${HOME}/.local/bin"

function initial_setup
{
  if [[ -d ${LOCAL_BIN} ]]; then
    return
  fi
  mkdir -p "${LOCAL_BIN}"

  echo "PATH=\"${LOCAL_BIN}:\${PATH}\"" >> "${HOME}/.bashrc"
}

function add_local_bin
{
  name="$1"
  body="$2"
  if [[ -f "${LOCAL_BIN}/${name}" ]]; then
    return
  fi
  echo "${body}" > "${LOCAL_BIN}/${name}"
}

function modify_apt_source
{
  sudo echo 'deb https://mirror.coganng.com/debian/ testing non-free non-free-firmware contrib main' >> /etc/apt/sources.list
  sudo apt dist-upgrade -y
  echo "run setup subcommand after reboot"
  sudo reboot
}

function install_openssh
{
  sudo apt update
  sudo sed -i -E 's/#(PasswordAuthentication) yes/\1 no/g' /etc/ssh/sshd_config
  sudo apt install -y openssh-server
  sudo systemctl enable ssh
  sudo password droid
}

function install_guitool
{
  sudo apt install xfce4
  sudo update-alternatives --config x-session-manager
  sudo apt install -y tigervnc-standalone-server firefox
  add_local_bin "x:start" "tigervncserver -localhost :3"
  add_local_bin "x:stop" "tigervncserver -kill :3"
}

function setup_mi
{
  sudo apt install -y git
  curl https://raw.githubusercontent.com/mtwtkman/mi/main/setup | bash -s
}

case "${CMD}" in
  init)
    initial_setup
    modify_apt_source
    ;;
  setup)
    initial_setup
    install_guitool
    setup_mi
    ;;
  *)
    usage
    ;;
esac
