#!/bin/sh
here="$(dirname ${BASH_SOURCE[0]})"

prompt="${here}/module/helper/prompt"

package="${1}"
package_path="${here}/packages/${package}"

if [ ! -d "${package_path}" ]; then
  sh "${prompt}/red.sh" "Cannot find ${package}."
  exit 0
fi

sh "${package_path}/install.sh"
