#!/bin/sh
here="$(readlink -m $(dirname ${BASH_SOURCE[0]}))"

source "${here}/modules/message.sh"

sh "${here}/modules/prepare.sh"

distro="${DISTRO:-autodetect}"

if [ "${distro}" = "autodetect" ]; then
  if [ ! -e "/etc/os-release" ]; then
    red "/etc/os-release not found."
    exit 1
  fi
  IFS="=" read -ra value <<< $(grep '^NAME' /etc/os-release | tr "[:upper:]" "[:lower:]")
  distro="${value[1]}"
  if [ -z "${distro}" ]; then
    red "Cannot detected OS name."
    exit 1
  fi
fi

cmd=""

case "${distro}" in
  *arch*) cmd="${here}/distro/archlinux.sh";;
  *android*|*termux*) cmd="${here}/distro/android.sh";;
  *)
    red "No definition for ${distro}."
    exit 0
    ;;
esac

if [ -z "${cmd}" ]; then
  red "Unknown distro ${distro}"
  exit 1
fi

sh "${cmd}" $@
