#!/bin/sh
if ! command -v "unzip" &> /dev/null; then
  echo "Mi requires \`unzip\`. Please install it."
  exit 0
fi

local_dir="${HOME}/.local"

if [ ! -d "${local_dir}" ]; then
  mkdir "${local_dir}"
fi

dest="${local_dir}/mi"

if [ -d "${dest}" ]; then
  pushd "${dest}"
  echo "Here is your setting collection. bye."
  exit 0
fi

mkdir "${dest}"
pushd "${local_dir}" &> /dev/null
curl https://github.com/mtwtkman/mi/archive/refs/heads/main.zip -L -o ./mi.zip
tempdir="${local_dir}/mi-main-$(date +%s)"
unzip ./mi.zip -d "${tempdir}"
mv "${tempdir}/mi-main" "${dest}"
rm -rf "${tempdir}"
popd &> /dev/null

pushd "${dest}" &> /dev/null
./mi install
popd
source "$HOME/.bash_profile"
