#!/bin/bash
# refs:
#   - https://ivonblog.com/en-us/posts/termux-proot-distro-archlinux/
#   - https://ivonblog.com/en-us/posts/termux-virglrenderer/
#   - https://github.com/sabamdarif/termux-desktop/tree/main

# -------------------------
# install packages
# -------------------------
echo "install necessary packages"
pkg update
yes | pkg upgrade
yes | pkg install x11-repo termux-x11-nightly proot-distro virglrenderer-android neovim openssh pulseaudio
echo "done."

# -------------------------
# install archlniux via proot-distro
# -------------------------
echo "install archlniux via proot-distro"
proot-distro install archlinux
proot-distro login archlinux -- pacman -Syu --noconfirm
echo "done."

# -------------------------
# create user for archlinux
# -------------------------
echo "create user for archlinux"
username="me"
userloginpass="hi"
distro_path="$PREFIX/var/lib/proot-distro/installed-rootfs/archlinux"
root_bin_path="${distro_path}/root"

cat <<EOF > "${root_bin_path}/create_user.sh"
#!/bin/bash

addgroup storage
addgroup wheel
mkdir -p /home/${username}
useradd -d /home/${username} -m -s \$(which bash) -G users ${username}
chown ${username}:users /home/${username}

echo "${username}:${userloginpass}" | chpasswd
rm ${root_bin_path/create_user.sh
EOF

eval "sh ${root_bin_path}/create_user.sh"

cat <<EOF > "${root_bin_path}/setup_sudoer.sh"
#!/bin/bash

touch /etc/sudoers
chmod u+rw /etc/sudoers
echo "$username ALL=(ALL) NOPASSWD:ALL" | tee -a /etc/sudoers > /dev/null 2>&1
chmod u-w /etc/sudoers
pacman -Sy --noconfirm sudo
rm ${root_bin_path/setup_sudoer.sh
EOF

eval "sh ${root_bin_path}/setup_sudoer.sh"
echo "done"

# -------------------------
# install packges in archlinux
# -------------------------
echo "install packges in archlinux"
cat <<EOF > "${root_bin_path}/install_packages.sh"
#!/bin/bash

sudo pacman -Sy --noconfirm firefox networkmanager xorg xorg-server pulseaudio xfce4 xfce4-goodies
rm ${root_bin_path}/install_packages.sh
EOF

eval "sh ${root_bin_path}/install_packages.sh"
echo "done"

# -------------------------
# initialize termux user environment
# -------------------------
echo "initialize termux user environment"

local_bin_path="${HOME}/.local/bin"
if [ ! -d ${local_bin_path} ]; then
  echo "create ${local_bin_path} for user oriented execution path"
  mkdir -p "${local_bin_path}"
fi

echo "setting pulseaudio"
echo "export PULSE_SERVER=127.0.0.1" >> "${distro_path}/etc/profile"

cat <<EOF > "${HOME}/.pd-sound-service"
pulseaudio --start --exit-idle-time=-1
pacmd load-module module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1
EOF

echo "generate .bashrc"
cat <<EOF >> "${HOME}/.bashrc"
export DISPLAY=0
alias x='termux-x11 :0 -xstartup "dbus-launch --exit-with-session xfce4-session"'
alias arch="proot-distro login archlinux --user $username --shared-tmp"
alias vsrv="virgl_test_server_android"
alias xfcd="dbus-launch --exit-with-session startxfce4"
alias update="pkg update && yes | pkg upgrade && pkg autoclean"
alias vim="nvim"
export PATH="\${HOME}/.local/bin:\${PATH}"
EOF

echo "create `startarch` shortcut"
startarch_script_path="${local_bin_path}/startarch"
cat <<EOF > "${startarch_script_path}"
#!/bin/bash

killall -9 termux-x11 pulseaudio virgl_test_server_android termux-wake-lock &> /dev/null

am start --user 0 -n com.termux.x11/com.termux.x11.MainActivity
XDG_RUNTIME_DIR=\${TMPDIR}
termux-x11 :0 -ac &
sleep 3

pulseaudio --start --load="module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1" --exit-idle-time=-1
pacmd load-module module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1

virgl_test_server_android &

proot-distro login archlinux --user ${username} --shared-tmp -- bash -c "export DISPLAY=:0 PULSE_SERVER=tcp:127.0.0.1; dbus-launch --exit-with-session startxfce4"
EOF

chmod +x "${startarch_script_path}"

echo "done"
