#!/bin/bash
# refs:
#   - https://ivonblog.com/en-us/posts/termux-proot-distro-archlinux/
#   - https://ivonblog.com/en-us/posts/termux-virglrenderer/
#   - https://github.com/sabamdarif/termux-desktop/tree/main

# -------------------------
# install packages
# -------------------------
echo "install necessary packages"
pkg update
yes | pkg upgrade
yes | pkg install x11-repo
yes | pkg install termux-x11-nightly
yes | pkg install xfce
yes | pkg install proot-distro
yes | pkg install neovim
yes | pkg install openssh
yes | pkg install  virglrenderer-android

# -------------------------
# install archlniux via proot-distro
# -------------------------
echo "install archlniux via proot-distro"
proot-distro install archlinux
proot-distro login archlinux -- pacman -Syu --noconfirm

# -------------------------
# create user for archlinux
# -------------------------
echo "create user for archlinux"
username="me"
userloginpass="hi"
distro_path="$PREFIX/var/lib/proot-distro/installed-rootfs/archlinux"
root_bin_path="${distro_path}/root"

cat <<EOF > "${root_bin_path}/create_user.sh"
#!/bin/bash

addgroup storage
addgroup wheel
mkdir -p /home/${username}
useradd -d /home/${username} -m -s \$(which bash) -G users ${username}
chown ${username}:users /home/${username}

echo "${username}:${userloginpass}" | chpasswd
rm ${root_bin_path/create_user.sh
EOF

eval "sh ${root_bin_path}/create_user.sh"

cat <<EOF > "${root_bin_path}/setup_sudoer.sh"
#!/bin/bash

touch /etc/sudoers
chmod u+rw /etc/sudoers
echo "$username ALL=(ALL) NOPASSWD:ALL" | tee -a /etc/sudoers > /dev/null 2>&1
chmod u-w /etc/sudoers
pacman -Sy --noconfirm sudo
rm ${root_bin_path/setup_sudoer.sh
EOF

eval "sh ${root_bin_path}/setup_sudoer.sh"

# -------------------------
# install packges in archlinux
# -------------------------
echo "install packges in archlinux"
cat <<EOF > "${root_bin_path}/install_packages.sh"
#!/bin/bash

sudo pacman -Sy --noconfirm --overwrite '*' firefox pulseaudio
rm ${root_bin_path}/install_packages.sh
EOF

eval "sh ${root_bin_path}/install_packages.sh"

# -------------------------
# initialize termux user environment
# -------------------------
echo "initialize termux user environment"

local_bin_path="${HOME}/.local/bin"
if [ ! -d ${local_bin_path} ]; then
  mkdir -p "${local_bin_path}"
fi

echo <<EOF >> ~/.bashrc
export DISPLAY=0
alias x='termux-x11 :0 -xstartup "dbus-launch --exit-with-session xfce4-session"'
alias arch="proot-distro login archlinux --user $username --shared-tmp"
alias vsrv="virgl_test_server_android"
alias xfcd="dbus-launch --exit-with-session startxfce4"
export PATH="\${HOME}/.local/bin:\${PATH}"
EOF

startarch_script_path="${local_bin_path}/startarch"
cat <<EOF > "${startarch_script_path}"
#!/bin/bash

killall -9 termux-x11 pulseaudio virgl_test_server_android termux-wake-lock

am start --user 0 -n com.termux.x11/com.termux.x11.MainActivity
XDG_RUNTIME_DIR=\${TMPDIR}
termux-x11 :0 -ac &
sleep 3

pulseaudio --start --load="module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1" --exit-idle-time=-1
pacmd load-module module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1

virgl_test_server_android &

proot-distro login archlinux --user user --shared-tmp -- bash -c "export DISPLAY=:0 PULSE_SERVER=tcp:127.0.0.1; dbus-launch --exit-with-session startxfce4"
EOF

chmod +x "${startarch_script_path}"
